# frozen_string_literal: true
source 'https://rubygems.org'

gem 'rake'

# Web framework
gem 'dry-web', '>= 0.6.0'
gem 'dry-web-roda', '>= 0.6.0'
gem 'puma'

gem 'rack', '>= 2.0'
gem 'shotgun', '>= 0.9.2'

# Application dependencies
gem 'dry-matcher'
gem 'dry-monads'
gem 'dry-struct'
gem 'dry-transaction'
gem 'dry-types'
gem 'dry-validation'

group :development, :test do
  gem 'pry-byebug', platform: :mri
  gem 'rubocop'
end

group :test do
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'poltergeist'
  gem 'rspec'
end
